name: Build and Push Docker Image to AWS ECR

permissions:
  contents: write     
on:
  push:
    tags:
      - "*"

env:
  AWS_REGION: 'ap-southeast-1'          # 例如: us-east-1
  ECR_REPOSITORY: 'maxfun-api'   # 例如: maxfun-api


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # AWS OIDC 鉴权
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tom
          role-session-name: GitHubAction-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      # 登录 ECR
      - name: ECR login
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      # 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max